export type SmartFieldObject = 'customer' | 'location' | 'equipment';
export type FieldDataType = 'text' | 'number' | 'date' | 'boolean' | 'dropdown' | 'phone' | 'email';

export interface SmartFieldDefinition {
  id: string;
  label: string;
  type: 'standard' | 'custom';
  dataType: FieldDataType;
  description?: string;
}

export const OBJECT_FIELDS: Record<SmartFieldObject, SmartFieldDefinition[]> = {
  customer: [
    // Standard fields
    { id: 'cust_name', label: 'Customer Name', type: 'standard', dataType: 'text' },
    { id: 'cust_email', label: 'Email Address', type: 'standard', dataType: 'email' },
    { id: 'cust_phone', label: 'Phone Number', type: 'standard', dataType: 'phone' },
    { id: 'cust_type', label: 'Customer Type', type: 'standard', dataType: 'dropdown' },
    { id: 'cust_since', label: 'Customer Since', type: 'standard', dataType: 'date' },
    { id: 'cust_balance', label: 'Account Balance', type: 'standard', dataType: 'number' },
    { id: 'cust_tax_exempt', label: 'Tax Exempt', type: 'standard', dataType: 'boolean' },
    { id: 'cust_referral', label: 'Referral Source', type: 'standard', dataType: 'dropdown' },
    // Custom fields
    { id: 'cf_cust_001', label: 'Preferred Contact Method', type: 'custom', dataType: 'dropdown', description: 'How customer prefers to be contacted' },
    { id: 'cf_cust_002', label: 'VIP Status', type: 'custom', dataType: 'boolean' },
    { id: 'cf_cust_003', label: 'Service Agreement Number', type: 'custom', dataType: 'text' },
    { id: 'cf_cust_004', label: 'Building Count', type: 'custom', dataType: 'number' },
    { id: 'cf_cust_005', label: 'HOA Contact Name', type: 'custom', dataType: 'text' },
    { id: 'cf_cust_006', label: 'HOA Phone', type: 'custom', dataType: 'phone' },
    { id: 'cf_cust_007', label: 'Warranty Expiration', type: 'custom', dataType: 'date' },
    { id: 'cf_cust_008', label: 'Annual Revenue Tier', type: 'custom', dataType: 'dropdown' },
    { id: 'cf_cust_009', label: 'Discount Rate (%)', type: 'custom', dataType: 'number' },
    { id: 'cf_cust_010', label: 'Secondary Email', type: 'custom', dataType: 'email' },
    { id: 'cf_cust_011', label: 'Property Manager Name', type: 'custom', dataType: 'text' },
    { id: 'cf_cust_012', label: 'Property Manager Phone', type: 'custom', dataType: 'phone' },
    { id: 'cf_cust_013', label: 'Fleet Size', type: 'custom', dataType: 'number' },
    { id: 'cf_cust_014', label: 'Insurance Provider', type: 'custom', dataType: 'text' },
    { id: 'cf_cust_015', label: 'Insurance Policy Number', type: 'custom', dataType: 'text' },
    { id: 'cf_cust_016', label: 'Credit Limit', type: 'custom', dataType: 'number' },
    { id: 'cf_cust_017', label: 'Net Terms', type: 'custom', dataType: 'dropdown' },
    { id: 'cf_cust_018', label: 'Preferred Technician', type: 'custom', dataType: 'text' },
    { id: 'cf_cust_019', label: 'Emergency Contact Name', type: 'custom', dataType: 'text' },
    { id: 'cf_cust_020', label: 'Emergency Contact Phone', type: 'custom', dataType: 'phone' },
    { id: 'cf_cust_021', label: 'Portal Access Enabled', type: 'custom', dataType: 'boolean' },
    { id: 'cf_cust_022', label: 'Marketing Opt-In', type: 'custom', dataType: 'boolean' },
    { id: 'cf_cust_023', label: 'Contract Start Date', type: 'custom', dataType: 'date' },
    { id: 'cf_cust_024', label: 'Contract End Date', type: 'custom', dataType: 'date' },
    { id: 'cf_cust_025', label: 'Industry Segment', type: 'custom', dataType: 'dropdown' },
    { id: 'cf_cust_026', label: 'Employee Count', type: 'custom', dataType: 'number' },
    { id: 'cf_cust_027', label: 'Square Footage Managed', type: 'custom', dataType: 'number' },
    { id: 'cf_cust_028', label: 'Seasonal Customer', type: 'custom', dataType: 'boolean' },
    { id: 'cf_cust_029', label: 'Language Preference', type: 'custom', dataType: 'dropdown' },
    { id: 'cf_cust_030', label: 'Time Zone', type: 'custom', dataType: 'dropdown' },
  ],
  location: [
    // Standard fields
    { id: 'loc_address', label: 'Street Address', type: 'standard', dataType: 'text' },
    { id: 'loc_city', label: 'City', type: 'standard', dataType: 'text' },
    { id: 'loc_state', label: 'State', type: 'standard', dataType: 'dropdown' },
    { id: 'loc_zip', label: 'ZIP Code', type: 'standard', dataType: 'text' },
    { id: 'loc_name', label: 'Location Name', type: 'standard', dataType: 'text' },
    { id: 'loc_type', label: 'Location Type', type: 'standard', dataType: 'dropdown' },
    { id: 'loc_phone', label: 'Location Phone', type: 'standard', dataType: 'phone' },
    { id: 'loc_zone', label: 'Service Zone', type: 'standard', dataType: 'text' },
    // Custom fields
    { id: 'cf_loc_001', label: 'Gate Code', type: 'custom', dataType: 'text' },
    { id: 'cf_loc_002', label: 'Alarm Code', type: 'custom', dataType: 'text' },
    { id: 'cf_loc_003', label: 'WiFi Network', type: 'custom', dataType: 'text' },
    { id: 'cf_loc_004', label: 'WiFi Password', type: 'custom', dataType: 'text' },
    { id: 'cf_loc_005', label: 'Year Built', type: 'custom', dataType: 'number' },
    { id: 'cf_loc_006', label: 'Square Footage', type: 'custom', dataType: 'number' },
    { id: 'cf_loc_007', label: 'Stories / Floors', type: 'custom', dataType: 'number' },
    { id: 'cf_loc_008', label: 'Roof Type', type: 'custom', dataType: 'dropdown' },
    { id: 'cf_loc_009', label: 'Roof Access Method', type: 'custom', dataType: 'text' },
    { id: 'cf_loc_010', label: 'Attic Access Location', type: 'custom', dataType: 'text' },
    { id: 'cf_loc_011', label: 'Crawl Space Access', type: 'custom', dataType: 'text' },
    { id: 'cf_loc_012', label: 'Gas Meter Location', type: 'custom', dataType: 'text' },
    { id: 'cf_loc_013', label: 'Water Main Location', type: 'custom', dataType: 'text' },
    { id: 'cf_loc_014', label: 'Electric Panel Location', type: 'custom', dataType: 'text' },
    { id: 'cf_loc_015', label: 'Number of Units', type: 'custom', dataType: 'number' },
    { id: 'cf_loc_016', label: 'HOA Managed', type: 'custom', dataType: 'boolean' },
    { id: 'cf_loc_017', label: 'HOA Name', type: 'custom', dataType: 'text' },
    { id: 'cf_loc_018', label: 'Parking Instructions', type: 'custom', dataType: 'text' },
    { id: 'cf_loc_019', label: 'Dog on Premises', type: 'custom', dataType: 'boolean' },
    { id: 'cf_loc_020', label: 'Key on File', type: 'custom', dataType: 'boolean' },
    { id: 'cf_loc_021', label: 'Key Box Code', type: 'custom', dataType: 'text' },
    { id: 'cf_loc_022', label: 'Site Contact Name', type: 'custom', dataType: 'text' },
    { id: 'cf_loc_023', label: 'Site Contact Phone', type: 'custom', dataType: 'phone' },
    { id: 'cf_loc_024', label: 'Preferred Service Window', type: 'custom', dataType: 'dropdown' },
    { id: 'cf_loc_025', label: 'Last Inspection Date', type: 'custom', dataType: 'date' },
    { id: 'cf_loc_026', label: 'Next Inspection Due', type: 'custom', dataType: 'date' },
    { id: 'cf_loc_027', label: 'Construction Type', type: 'custom', dataType: 'dropdown' },
    { id: 'cf_loc_028', label: 'Occupancy Type', type: 'custom', dataType: 'dropdown' },
    { id: 'cf_loc_029', label: 'Permit Number', type: 'custom', dataType: 'text' },
    { id: 'cf_loc_030', label: 'Geographic Region', type: 'custom', dataType: 'dropdown' },
  ],
  equipment: [
    // Standard fields
    { id: 'eq_name', label: 'Equipment Name', type: 'standard', dataType: 'text' },
    { id: 'eq_make', label: 'Make / Brand', type: 'standard', dataType: 'text' },
    { id: 'eq_model', label: 'Model Number', type: 'standard', dataType: 'text' },
    { id: 'eq_serial', label: 'Serial Number', type: 'standard', dataType: 'text' },
    { id: 'eq_install_date', label: 'Install Date', type: 'standard', dataType: 'date' },
    { id: 'eq_warranty_exp', label: 'Warranty Expiration', type: 'standard', dataType: 'date' },
    { id: 'eq_type', label: 'Equipment Type', type: 'standard', dataType: 'dropdown' },
    { id: 'eq_status', label: 'Equipment Status', type: 'standard', dataType: 'dropdown' },
    // Custom fields
    { id: 'cf_eq_001', label: 'Tonnage / Capacity', type: 'custom', dataType: 'number' },
    { id: 'cf_eq_002', label: 'SEER Rating', type: 'custom', dataType: 'number' },
    { id: 'cf_eq_003', label: 'AFUE Rating', type: 'custom', dataType: 'number' },
    { id: 'cf_eq_004', label: 'Refrigerant Type', type: 'custom', dataType: 'dropdown' },
    { id: 'cf_eq_005', label: 'Refrigerant Amount (lbs)', type: 'custom', dataType: 'number' },
    { id: 'cf_eq_006', label: 'Filter Size', type: 'custom', dataType: 'text' },
    { id: 'cf_eq_007', label: 'Filter Change Interval', type: 'custom', dataType: 'dropdown' },
    { id: 'cf_eq_008', label: 'Last Filter Change', type: 'custom', dataType: 'date' },
    { id: 'cf_eq_009', label: 'Next Service Due', type: 'custom', dataType: 'date' },
    { id: 'cf_eq_010', label: 'Location on Property', type: 'custom', dataType: 'text' },
    { id: 'cf_eq_011', label: 'Electrical Specs', type: 'custom', dataType: 'text' },
    { id: 'cf_eq_012', label: 'Voltage', type: 'custom', dataType: 'number' },
    { id: 'cf_eq_013', label: 'Amperage', type: 'custom', dataType: 'number' },
    { id: 'cf_eq_014', label: 'Fuel Type', type: 'custom', dataType: 'dropdown' },
    { id: 'cf_eq_015', label: 'Gas Pressure (inches WC)', type: 'custom', dataType: 'number' },
    { id: 'cf_eq_016', label: 'BTU Input', type: 'custom', dataType: 'number' },
    { id: 'cf_eq_017', label: 'BTU Output', type: 'custom', dataType: 'number' },
    { id: 'cf_eq_018', label: 'Condition Rating', type: 'custom', dataType: 'dropdown' },
    { id: 'cf_eq_019', label: 'Age (Years)', type: 'custom', dataType: 'number' },
    { id: 'cf_eq_020', label: 'Replacement Recommended', type: 'custom', dataType: 'boolean' },
    { id: 'cf_eq_021', label: 'Under Service Contract', type: 'custom', dataType: 'boolean' },
    { id: 'cf_eq_022', label: 'Contract Number', type: 'custom', dataType: 'text' },
    { id: 'cf_eq_023', label: 'Parts Warranty Active', type: 'custom', dataType: 'boolean' },
    { id: 'cf_eq_024', label: 'Labor Warranty Active', type: 'custom', dataType: 'boolean' },
    { id: 'cf_eq_025', label: 'Thermostat Brand', type: 'custom', dataType: 'text' },
    { id: 'cf_eq_026', label: 'Thermostat Model', type: 'custom', dataType: 'text' },
    { id: 'cf_eq_027', label: 'Control Board Part #', type: 'custom', dataType: 'text' },
    { id: 'cf_eq_028', label: 'Coil Type', type: 'custom', dataType: 'dropdown' },
    { id: 'cf_eq_029', label: 'Duct Configuration', type: 'custom', dataType: 'text' },
    { id: 'cf_eq_030', label: 'Photo on File', type: 'custom', dataType: 'boolean' },
  ],
};
