export type SmartFieldObject = 'general' | 'customer' | 'location' | 'equipment';
export type FieldDataType = 'text' | 'number' | 'date' | 'boolean' | 'dropdown' | 'phone' | 'email';
export type FieldKind = 'system' | 'custom';

export interface SmartFieldDefinition {
  id: string;
  label: string;
  kind: FieldKind;       // 'system' = built-in ST field | 'custom' = tenant-created
  dataType: FieldDataType;
  description?: string;
}

export const OBJECT_FIELDS: Record<SmartFieldObject, SmartFieldDefinition[]> = {
  // General — system fields only (matches ST current smart field list)
  general: [
    { id: 'gen_bill_to_address',                    label: 'Bill-to Address',                        kind: 'system', dataType: 'text' },
    { id: 'gen_business_unit',                      label: 'Business Unit',                          kind: 'system', dataType: 'text' },
    { id: 'gen_campaign',                           label: 'Campaign',                               kind: 'system', dataType: 'text' },
    { id: 'gen_customer_balance',                   label: 'Customer Balance',                       kind: 'system', dataType: 'number' },
    { id: 'gen_customer_email',                     label: 'Customer Email',                         kind: 'system', dataType: 'email' },
    { id: 'gen_customer_name',                      label: 'Customer Name',                          kind: 'system', dataType: 'text' },
    { id: 'gen_customer_phone_number',              label: 'Customer Phone Number',                  kind: 'system', dataType: 'phone' },
    { id: 'gen_customer_type',                      label: 'Customer Type',                          kind: 'system', dataType: 'dropdown' },
    { id: 'gen_equipment_cost',                     label: 'Equipment Cost',                         kind: 'system', dataType: 'number' },
    { id: 'gen_equipment_installed_on',             label: 'Equipment Installed On',                 kind: 'system', dataType: 'date' },
    { id: 'gen_equipment_manufacturer',             label: 'Equipment Manufacturer',                 kind: 'system', dataType: 'text' },
    { id: 'gen_equipment_mfr_warranty_end',         label: 'Equipment Manufacturer Warranty End',    kind: 'system', dataType: 'date' },
    { id: 'gen_equipment_mfr_warranty_start',       label: 'Equipment Manufacturer Warranty Start',  kind: 'system', dataType: 'date' },
    { id: 'gen_equipment_memo',                     label: 'Equipment Memo',                         kind: 'system', dataType: 'text' },
    { id: 'gen_equipment_model',                    label: 'Equipment Model',                        kind: 'system', dataType: 'text' },
    { id: 'gen_equipment_name',                     label: 'Equipment Name',                         kind: 'system', dataType: 'text' },
    { id: 'gen_equipment_sp_warranty_end',          label: 'Equipment Service Provider Warranty End',   kind: 'system', dataType: 'date' },
    { id: 'gen_equipment_sp_warranty_start',        label: 'Equipment Service Provider Warranty Start', kind: 'system', dataType: 'date' },
    { id: 'gen_equipment_serial_number',            label: 'Equipment Serial Number',                kind: 'system', dataType: 'text' },
    { id: 'gen_equipment_type',                     label: 'Equipment Type',                         kind: 'system', dataType: 'dropdown' },
    { id: 'gen_job_number',                         label: 'Job Number',                             kind: 'system', dataType: 'text' },
    { id: 'gen_job_priority',                       label: 'Job Priority',                           kind: 'system', dataType: 'dropdown' },
    { id: 'gen_job_start_date',                     label: 'Job Start Date',                         kind: 'system', dataType: 'date' },
    { id: 'gen_job_start_time',                     label: 'Job Start Time',                         kind: 'system', dataType: 'text' },
    { id: 'gen_job_type',                           label: 'Job Type',                               kind: 'system', dataType: 'dropdown' },
    { id: 'gen_location_address',                   label: 'Location Address',                       kind: 'system', dataType: 'text' },
    { id: 'gen_location_email',                     label: 'Location Email',                         kind: 'system', dataType: 'email' },
    { id: 'gen_location_name',                      label: 'Location Name',                          kind: 'system', dataType: 'text' },
    { id: 'gen_location_phone_number',              label: 'Location Phone Number',                  kind: 'system', dataType: 'phone' },
    { id: 'gen_project_name',                       label: 'Project Name',                           kind: 'system', dataType: 'text' },
    { id: 'gen_project_number',                     label: 'Project Number',                         kind: 'system', dataType: 'text' },
    { id: 'gen_tax_zone',                           label: 'Tax Zone',                               kind: 'system', dataType: 'text' },
    { id: 'gen_technician_license',                 label: 'Technician License',                     kind: 'system', dataType: 'text' },
    { id: 'gen_technician_name',                    label: 'Technician Name',                        kind: 'system', dataType: 'text' },
    { id: 'gen_todays_date',                        label: "Today's Date",                           kind: 'system', dataType: 'date' },
    { id: 'gen_zone',                               label: 'Zone',                                   kind: 'system', dataType: 'text' },
  ],

  customer: [
    // System fields
    { id: 'cust_name',       label: 'Customer Name',    kind: 'system', dataType: 'text' },
    { id: 'cust_email',      label: 'Email Address',    kind: 'system', dataType: 'email' },
    { id: 'cust_phone',      label: 'Phone Number',     kind: 'system', dataType: 'phone' },
    { id: 'cust_type',       label: 'Customer Type',    kind: 'system', dataType: 'dropdown' },
    { id: 'cust_since',      label: 'Customer Since',   kind: 'system', dataType: 'date' },
    { id: 'cust_balance',    label: 'Account Balance',  kind: 'system', dataType: 'number' },
    { id: 'cust_tax_exempt', label: 'Tax Exempt',       kind: 'system', dataType: 'boolean' },
    { id: 'cust_referral',   label: 'Referral Source',  kind: 'system', dataType: 'dropdown' },
    // Custom fields
    { id: 'cf_cust_001', label: 'Preferred Contact Method',  kind: 'custom', dataType: 'dropdown', description: 'How customer prefers to be contacted' },
    { id: 'cf_cust_002', label: 'VIP Status',                kind: 'custom', dataType: 'boolean' },
    { id: 'cf_cust_003', label: 'Service Agreement Number',  kind: 'custom', dataType: 'text' },
    { id: 'cf_cust_004', label: 'Building Count',            kind: 'custom', dataType: 'number' },
    { id: 'cf_cust_005', label: 'HOA Contact Name',          kind: 'custom', dataType: 'text' },
    { id: 'cf_cust_006', label: 'HOA Phone',                 kind: 'custom', dataType: 'phone' },
    { id: 'cf_cust_007', label: 'Warranty Expiration',       kind: 'custom', dataType: 'date' },
    { id: 'cf_cust_008', label: 'Annual Revenue Tier',       kind: 'custom', dataType: 'dropdown' },
    { id: 'cf_cust_009', label: 'Discount Rate (%)',         kind: 'custom', dataType: 'number' },
    { id: 'cf_cust_010', label: 'Secondary Email',           kind: 'custom', dataType: 'email' },
    { id: 'cf_cust_011', label: 'Property Manager Name',     kind: 'custom', dataType: 'text' },
    { id: 'cf_cust_012', label: 'Property Manager Phone',    kind: 'custom', dataType: 'phone' },
    { id: 'cf_cust_013', label: 'Fleet Size',                kind: 'custom', dataType: 'number' },
    { id: 'cf_cust_014', label: 'Insurance Provider',        kind: 'custom', dataType: 'text' },
    { id: 'cf_cust_015', label: 'Insurance Policy Number',   kind: 'custom', dataType: 'text' },
    { id: 'cf_cust_016', label: 'Credit Limit',              kind: 'custom', dataType: 'number' },
    { id: 'cf_cust_017', label: 'Net Terms',                 kind: 'custom', dataType: 'dropdown' },
    { id: 'cf_cust_018', label: 'Preferred Technician',      kind: 'custom', dataType: 'text' },
    { id: 'cf_cust_019', label: 'Emergency Contact Name',    kind: 'custom', dataType: 'text' },
    { id: 'cf_cust_020', label: 'Emergency Contact Phone',   kind: 'custom', dataType: 'phone' },
    { id: 'cf_cust_021', label: 'Portal Access Enabled',     kind: 'custom', dataType: 'boolean' },
    { id: 'cf_cust_022', label: 'Marketing Opt-In',          kind: 'custom', dataType: 'boolean' },
    { id: 'cf_cust_023', label: 'Contract Start Date',       kind: 'custom', dataType: 'date' },
    { id: 'cf_cust_024', label: 'Contract End Date',         kind: 'custom', dataType: 'date' },
    { id: 'cf_cust_025', label: 'Industry Segment',          kind: 'custom', dataType: 'dropdown' },
    { id: 'cf_cust_026', label: 'Employee Count',            kind: 'custom', dataType: 'number' },
    { id: 'cf_cust_027', label: 'Square Footage Managed',    kind: 'custom', dataType: 'number' },
    { id: 'cf_cust_028', label: 'Seasonal Customer',         kind: 'custom', dataType: 'boolean' },
    { id: 'cf_cust_029', label: 'Language Preference',       kind: 'custom', dataType: 'dropdown' },
    { id: 'cf_cust_030', label: 'Time Zone',                 kind: 'custom', dataType: 'dropdown' },
  ],

  location: [
    // System fields
    { id: 'loc_address', label: 'Street Address',  kind: 'system', dataType: 'text' },
    { id: 'loc_city',    label: 'City',             kind: 'system', dataType: 'text' },
    { id: 'loc_state',   label: 'State',            kind: 'system', dataType: 'dropdown' },
    { id: 'loc_zip',     label: 'ZIP Code',         kind: 'system', dataType: 'text' },
    { id: 'loc_name',    label: 'Location Name',    kind: 'system', dataType: 'text' },
    { id: 'loc_type',    label: 'Location Type',    kind: 'system', dataType: 'dropdown' },
    { id: 'loc_phone',   label: 'Location Phone',   kind: 'system', dataType: 'phone' },
    { id: 'loc_zone',    label: 'Service Zone',     kind: 'system', dataType: 'text' },
    // Custom fields
    { id: 'cf_loc_001', label: 'Gate Code',                 kind: 'custom', dataType: 'text' },
    { id: 'cf_loc_002', label: 'Alarm Code',                kind: 'custom', dataType: 'text' },
    { id: 'cf_loc_003', label: 'WiFi Network',              kind: 'custom', dataType: 'text' },
    { id: 'cf_loc_004', label: 'WiFi Password',             kind: 'custom', dataType: 'text' },
    { id: 'cf_loc_005', label: 'Year Built',                kind: 'custom', dataType: 'number' },
    { id: 'cf_loc_006', label: 'Square Footage',            kind: 'custom', dataType: 'number' },
    { id: 'cf_loc_007', label: 'Stories / Floors',          kind: 'custom', dataType: 'number' },
    { id: 'cf_loc_008', label: 'Roof Type',                 kind: 'custom', dataType: 'dropdown' },
    { id: 'cf_loc_009', label: 'Roof Access Method',        kind: 'custom', dataType: 'text' },
    { id: 'cf_loc_010', label: 'Attic Access Location',     kind: 'custom', dataType: 'text' },
    { id: 'cf_loc_011', label: 'Crawl Space Access',        kind: 'custom', dataType: 'text' },
    { id: 'cf_loc_012', label: 'Gas Meter Location',        kind: 'custom', dataType: 'text' },
    { id: 'cf_loc_013', label: 'Water Main Location',       kind: 'custom', dataType: 'text' },
    { id: 'cf_loc_014', label: 'Electric Panel Location',   kind: 'custom', dataType: 'text' },
    { id: 'cf_loc_015', label: 'Number of Units',           kind: 'custom', dataType: 'number' },
    { id: 'cf_loc_016', label: 'HOA Managed',               kind: 'custom', dataType: 'boolean' },
    { id: 'cf_loc_017', label: 'HOA Name',                  kind: 'custom', dataType: 'text' },
    { id: 'cf_loc_018', label: 'Parking Instructions',      kind: 'custom', dataType: 'text' },
    { id: 'cf_loc_019', label: 'Dog on Premises',           kind: 'custom', dataType: 'boolean' },
    { id: 'cf_loc_020', label: 'Key on File',               kind: 'custom', dataType: 'boolean' },
    { id: 'cf_loc_021', label: 'Key Box Code',              kind: 'custom', dataType: 'text' },
    { id: 'cf_loc_022', label: 'Site Contact Name',         kind: 'custom', dataType: 'text' },
    { id: 'cf_loc_023', label: 'Site Contact Phone',        kind: 'custom', dataType: 'phone' },
    { id: 'cf_loc_024', label: 'Preferred Service Window',  kind: 'custom', dataType: 'dropdown' },
    { id: 'cf_loc_025', label: 'Last Inspection Date',      kind: 'custom', dataType: 'date' },
    { id: 'cf_loc_026', label: 'Next Inspection Due',       kind: 'custom', dataType: 'date' },
    { id: 'cf_loc_027', label: 'Construction Type',         kind: 'custom', dataType: 'dropdown' },
    { id: 'cf_loc_028', label: 'Occupancy Type',            kind: 'custom', dataType: 'dropdown' },
    { id: 'cf_loc_029', label: 'Permit Number',             kind: 'custom', dataType: 'text' },
    { id: 'cf_loc_030', label: 'Geographic Region',         kind: 'custom', dataType: 'dropdown' },
  ],

  equipment: [
    // System fields
    { id: 'eq_name',         label: 'Equipment Name',      kind: 'system', dataType: 'text' },
    { id: 'eq_make',         label: 'Make / Brand',        kind: 'system', dataType: 'text' },
    { id: 'eq_model',        label: 'Model Number',        kind: 'system', dataType: 'text' },
    { id: 'eq_serial',       label: 'Serial Number',       kind: 'system', dataType: 'text' },
    { id: 'eq_install_date', label: 'Install Date',        kind: 'system', dataType: 'date' },
    { id: 'eq_warranty_exp', label: 'Warranty Expiration', kind: 'system', dataType: 'date' },
    { id: 'eq_type',         label: 'Equipment Type',      kind: 'system', dataType: 'dropdown' },
    { id: 'eq_status',       label: 'Equipment Status',    kind: 'system', dataType: 'dropdown' },
    // Custom fields
    { id: 'cf_eq_001', label: 'Tonnage / Capacity',        kind: 'custom', dataType: 'number' },
    { id: 'cf_eq_002', label: 'SEER Rating',               kind: 'custom', dataType: 'number' },
    { id: 'cf_eq_003', label: 'AFUE Rating',               kind: 'custom', dataType: 'number' },
    { id: 'cf_eq_004', label: 'Refrigerant Type',          kind: 'custom', dataType: 'dropdown' },
    { id: 'cf_eq_005', label: 'Refrigerant Amount (lbs)',  kind: 'custom', dataType: 'number' },
    { id: 'cf_eq_006', label: 'Filter Size',               kind: 'custom', dataType: 'text' },
    { id: 'cf_eq_007', label: 'Filter Change Interval',    kind: 'custom', dataType: 'dropdown' },
    { id: 'cf_eq_008', label: 'Last Filter Change',        kind: 'custom', dataType: 'date' },
    { id: 'cf_eq_009', label: 'Next Service Due',          kind: 'custom', dataType: 'date' },
    { id: 'cf_eq_010', label: 'Location on Property',      kind: 'custom', dataType: 'text' },
    { id: 'cf_eq_011', label: 'Electrical Specs',          kind: 'custom', dataType: 'text' },
    { id: 'cf_eq_012', label: 'Voltage',                   kind: 'custom', dataType: 'number' },
    { id: 'cf_eq_013', label: 'Amperage',                  kind: 'custom', dataType: 'number' },
    { id: 'cf_eq_014', label: 'Fuel Type',                 kind: 'custom', dataType: 'dropdown' },
    { id: 'cf_eq_015', label: 'Gas Pressure (inches WC)',  kind: 'custom', dataType: 'number' },
    { id: 'cf_eq_016', label: 'BTU Input',                 kind: 'custom', dataType: 'number' },
    { id: 'cf_eq_017', label: 'BTU Output',                kind: 'custom', dataType: 'number' },
    { id: 'cf_eq_018', label: 'Condition Rating',          kind: 'custom', dataType: 'dropdown' },
    { id: 'cf_eq_019', label: 'Age (Years)',               kind: 'custom', dataType: 'number' },
    { id: 'cf_eq_020', label: 'Replacement Recommended',   kind: 'custom', dataType: 'boolean' },
    { id: 'cf_eq_021', label: 'Under Service Contract',    kind: 'custom', dataType: 'boolean' },
    { id: 'cf_eq_022', label: 'Contract Number',           kind: 'custom', dataType: 'text' },
    { id: 'cf_eq_023', label: 'Parts Warranty Active',     kind: 'custom', dataType: 'boolean' },
    { id: 'cf_eq_024', label: 'Labor Warranty Active',     kind: 'custom', dataType: 'boolean' },
    { id: 'cf_eq_025', label: 'Thermostat Brand',          kind: 'custom', dataType: 'text' },
    { id: 'cf_eq_026', label: 'Thermostat Model',          kind: 'custom', dataType: 'text' },
    { id: 'cf_eq_027', label: 'Control Board Part #',      kind: 'custom', dataType: 'text' },
    { id: 'cf_eq_028', label: 'Coil Type',                 kind: 'custom', dataType: 'dropdown' },
    { id: 'cf_eq_029', label: 'Duct Configuration',        kind: 'custom', dataType: 'text' },
    { id: 'cf_eq_030', label: 'Photo on File',             kind: 'custom', dataType: 'boolean' },
  ],
};
